version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "grassley-schedule-notifier"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9mtg9q891by0"
s3_prefix = "grassley-schedule-notifier"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Sender=\"grassley@dmichael.be\" Recipient=\"1.david.michael@gmail.com\""
